name: Update README Activity

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README with activity
        uses: Readme-Workflows/recent-activity@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
